name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - name: Node
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install Dependencies
        run: |
          npm i

      - name: Build
        run: |
          npm run build-production

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.4
        with:
          BRANCH: gh-pages
          FOLDER: docs
          single-commit: true
